<a href="https://colab.research.google.com/github/YTFarhan/London_Bike_Sharing_Data_Analysis/blob/main/London_Bike_Share_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install pandas
!pip install kagglehub

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [4]:
import pandas as pd
import zipfile

In [5]:
# uploading file
from google.colab import files
files.upload()

Saving archive.zip to archive.zip

{'archive.zip': b'PK\x03\x04-\x00\x00\x00\x08\x004fJO\xf5!L\x04\xff\xff\xff\xff\xff\xff\xff\xff\x11\x00\x14\x00london_merged.csv\x01\x00\x10\x00E\xca\x0f\x00\x00\x00\x00\x00\x8b\x94\x02\x00\x00\x00\x00\x00\x94\x9di\xcel9\x8e\x9e\xff{\x15^\xc0w\x03\x9a\x07o\xa6\xd1p%\xd0\r\xbb\x07\xb8\xcahx\xf7\xfe\x0e%\xf2\xe5\x19\x82\x8c\x00:og\xa2\xe2\xb9\x1a\x8eDQ\x9c\xf4\x8f\x7f\xfd\xb7\xbf\xfe\xfe\x8f\x7f\xfe\xb7\xff\xfc\xf9\x9f\xff\xfe\x8f\x9f\x7f\xc4\x9f\x7f\xa4\x9f\x7f\xf9\xbf\xff\xf6\xf3_\xff\xfa\xef\x7f\xfb\xa7\xbf\xff\xe7_\x7f\xfd\xed\xe7\xbf\xfe\xfa\xe7\x7f\xfc\xcb_\xff\xe7\x9f\xfe\xe7\x7f\xfc\xed\xaf\x9f\x7f\xfd\xfb?\xfd\xcb\x7f\xfc\xef\x7f\xfd\xdb?\xff\xbf\xe3_\xff\xeb\xaf\xbf\xfe\xd7_\xff\xfe\xb7\x9f\xbf\xff\xf5\xcf\x7f\xff\x8f\x7f\xffo)\xc4\xfa\'\xc4?\xa1\xfc\xf7\x10\xfe\x07\xfd\xdfO\x1c\xe9\'\xbf\xc2O\xfa\xfdg\x1e\xff\xd2~\xff9\xfe\x7f\xf8\xfd\'\xae\x7f?\x81\x91\xc1<6X\x17X7\xf0\x0eL\x02\x16\x82\x08l\xbf\x7f\x04\x07\xcc\x1b\xec\x89zy\xfc\x13CP\xc0;\xb0l\xb0t\x82\x02\x86XM\xae2\xd7\xa4A\xe2\x8a\xd3^\xdb\\\x8d\xf4?\xff\x89\xd2\xd3\xbe\xe9wd\xe7!\xd6o\xc9!\xb3z4Z\x17J\xd3:\x1crn2\x87HC\xfc\x13\x8ei\xa1F\xe7\xcb\\\x03\x91\x17OMk\r\x10JS\x14\x93\x83\xf2\xf2\xe9i}\x94?QZuY^A\xa3%\xb04\xd6\xc8\x9f\xe7\x1d\xcakh\xc6\x86\x1e\x8fcrcuZ\xe5U\x14C\x9e\xb4hi\x86\x8e?\x86CV\xe9\xefT\xfd\xa5i\x8a\x0e\xcaK\xa9\xe7.\xbf\xfbl\x82y)\xd5Y.\xa4\xd7&/\xa5\x9a\x96H\x90\xde\x1e3l\x81\xb2\x92\xfa\xdc\xe0n\xb2\xdb-&^Gy\xaf\xa3\xfcR;\xcd\x02y\x15\xa5\x14\xe9w\'!d\xac\x83$B\xa8\xb3\xf4Rb\xcf\x02y\x01\xc5\xdaw\xef\xf6\xfa1[\xac\x10\xb4#\xcb\xa8n\r\x86\x07\x8e\x87\xd8\xd0\xdem\x84O\x1c\x8f0\'\xf9)\xf5\xd3k\x8f\x07\xf8\xfb\xf1\xd7O\x7f\xc7w\xfc\xbe\xff\xfe\x8b\xc5\xf1\xf6\xf8=\x0e\x8eur\xb4I\x9c\x16?O\x9cl\x8eH\xed\xd5\xa7\xf9|\xe2xg\x94R~\xd6\xb8~\xc1\xb8\xc1l\x80\xbc1b\x9d\xfd\x87g\x84H\xbd\xbe\x9fH\xde\x189\xb6H\xe3:\xe6\xa4\xcf\x0f\xda\xe4\x9d\xf1{\xe6\xa5M\xfe\xb6\x99^\xe7c\xf6\x81\x84\x88m\x83\xc4\xf1\x01\x8f\xe3\xa38\x9d\x15\x01[G!\xf0\xe8\xeb\\\xa2\xddi\x92WN\xff\x15\xaf\xf4cj\x93\x8e\xf5\xe8\xa0\xbcxF\xcf\x8c\xd65N\xb7U^?\xad\xefV\'O\xd1tHYA\xa1\xa3Q\xfa,n\xa3\xbc\x88b\x9cI\xb1\x99\x8f\x12\x8b\xe5u\x94\xfa\xefj\x98\x07&hrP^H)\x8f)h\xa3\x1e\x17\x07\x95\x95\x94\xfa\xfa\xae\xc7:\xe8\xf1\x03T\xa4l\x9bm\xaf\x88\xf0!\xc9k\xa9\xc4x!\x9d\x05\x91 \x85\xb0\n\x17y\xfc\xda\xd8\xdf\x10\xb43\xad\x8f\xc2\xb3k\n\x94\x06A;\xd7\x1e\xa5\xf9\xa1-\xeep\xa2\x91\xe4\xef8\x19"saq47\x16\x88\x11\x12X\xb9A\xfa\x1c\x16(\xfa\xecZ\xaeM\xd6\x9d\xd7"\xef\x94\xdf\xa5\xc3-\xae\xcd\xe9\xb5(\x1am\x0e\x9b\xdcR(\x9a\x92\xaf)i\xdbc\x95\xb5\xb3\x1a\xcd\x0e*\xe2\xb6\xe6rA\xd3\xfe\xafw\xa8\xec\x92\xfa\xfb5y\x97,5\xaf\xd9\xa8\x08\xdc\x96\xb7\xa8<\x16\xde8\x06\x1d\xa7%r\x9b\x12\xb95(\xc1I\xa8V\x11\x9fPYDs\x7fF\xfac\t]\x1e\xfa;\x96\xd7QI\x8d\x84\t-\xda\xe3\xe3\xa4\xeet\x98\x17R\xeds\xcf\xd2\xde\xd7\xc9<\x96\x1adn\x8fco\x90\xbd\xaf\xd3A%\x83\x84\xc8\x1dE\xd6R;\xd61\xcd\xaf\x85\x8a\xc4m\xbf\'\x13\xeb#\xabUZ\x15\x06*\x12\xb7E\xdc\xa5\x96 :\xfe"\x0b\x95\xb5TB\x92\xe3zmT}\xd5}@E\xe2\xf6\xb46\xdb\xa1\x9e\xf6\xc1\xdb\xc6"E\xe2\xfej\xefu\xcf(\xe9(.)+\xe9W/\xa2\x1d\xfa\xdaz\x11\xed7\x8b\x14\xcd/&\xb9\xe2\x92\n\x17\xcd\xd9\xed\xca\x88\x10\x14\x19?!E\xbb\r\x170:\xa0\x92\xba\x0b\xe4Q\x06\x07\x94Q\x1e\x17\xc0\x8aA\x1e\xeb?\x19\\\xb1\x1a\xb4@\xa8\'\x04\xd2\x97\xec\xbbA\xab\xa3"s\x7f{\xba\x96\xc0\xa7C\x84\xcc\xfd\xbd\xa4\xf0\xba\xfb`\rt%s[\x1c[\xc5\xacj\xe1Y\xe3\x94}\xd2#6\xf6\xda\'\xa6\x06\xd7!s{\xcb8^\xd2"\xab\xd5\xa8\x88\xdc6\x03$\xd8\xf1G\x8avwE\xe2\xce\xb8N\x089~SwH\xb1!\x8c$\xf2\xb6\x1f\xeb!\r\x87\xe45\xd4\xc7V\x8f\x8f\x19n\x07\x91\x863P\x11\xb8\xb3\xc8@Ij&\xe7\xbb(\x81\xdb\xe3e\x8e\xcc\xc3\xbbk\x81[\xfa\x1ej\xddC-\x0e*\x02\xf78[\xf69\xba%n\x0e6\x0bE\xb5vL\x13)\xf49X\'Z\x87\xdc\xac\xb1\xa1UZJ\xf4Y\xbb\x81\xf2\x82(\xbf\xcb\xf7KTdJ\xd0\xad\xd2\x87)\x16:\x94\xe8LY\x1f\xfc\xd4\xacyU\x1f\x10\x9e\xb5\x1dT]\x7f\xa0\xd9l\xa0<\xd8\xc3D)\x1a\xd5j\xb5:(\x0f\xf6W\x10*\x94ZM\x0e*24i\x94v\xcd\xf1a\xady\x12)\xda5\x1a>Aa\x8e\x8dj\x9e:\x1d\x8e\xda2\xf5\xc4\xf2\x0e8\xf6z$\xeb\xe6\x8bt\xe6\x8dZ\xcd\x8aE6\xa5!\x97\xbcA\xda\x86\xb7(X\x94\xb2\xf6J\xcb\x89\xb4\xd7l\x93"I\xe3\xa8\x17\xd2iS$i\x9cY\xa4\xc4Z\x10\xce\xfc\x8a$=\xec\x85\xa2k\xcb\xec&\x83\xe4\xa5t\xdc\xf9E\x06\xd3A\xec\x91"I\x7f\xef\xdeg\xe9B\x8b\xd0BE\x92\x0e%\x0e?"E\x92\x1e\x1a\xd2\t\xb5\xcf\xa9\xa1$i\xaeW!\xec\xb5*\x924\xc6u\xdf\xa3Y:\xce\xe5D\xeb\xd0@a,\xc8\x13G2\xa1\xc1F\xa1\xba\xd6t9\xcci5\x19\xa4\xa8\xae\xbf\xd2[\xae\x064R\xafM\x91\xc0)_\x06jj\x83C\t\xe0\xd6\xbf9\xcc\xa7\x92\xbf\xa5_\x17\xd2pP\xa5\xbb\x82<\xba\x9b\xf9\xbf\xde\x91<\xd0V/\xe7[\x9a\xd6^\x9b\x10\xbe%\xa9\xd3\xa2\xd3\xea3\x95\xacy\xf2\x82]n\x989;\xa8\x08\xdfz=h\\\x14f\xda\xdbI\x93\x8f\xe5k\xb1\xcaR\x9bopt`X\x0fBU\xf0\x9a+Sg\x9aZ\x97mC\xc3\x85\xbf\xae\x01C\x9b\x9d\xf3\xc0\xea\xfa\xa3\xed\x8fdl\x81\t)<\x0eM\xe2\x18\x1e\xfd\xd1h\x15\x93!\xc1`\xc5\xa7\x11~\xf7\xec\x15n\x0e,\xc6\xa8\xd0\x87\x86\xe9\xfb\x06\x07\xe6\xa55{\xbb\xb2\xd4\xb05[\xbc\xb6f\xa4N\xd7\xf5G#\xd3E\xb6w\x83\x12\xc8i\xaa\x86\xe9\x1bg\xf3|\x9eJ$\x970U\xcbkYW\x07\x96\xc3}\x1e\xaa<\xdd\xc9\xe5\xd2\x92\x9b\x03\xcb\xea\n\xbf\xca|<d\x15\xfd\xd1\x0f\xa6D\x1b\x86r<\x9aj\xb8\x1f\r\x17S\xeb\x9bJ4\x17\xdd\xe96\xb8]\x8b\x15\xe1\xdc\xca\x8d\r\x0e\x0b\xa9\x15\x96"\xb2\xb4\x91=\xde\xf7~\xa5\x18 \xa0\xf3a\xa1?\xb3\xf9\x10y\xcc\xc6\x07V\xdc\x83\xbd\xdf\xda\r\x0e+\xbbiL\xcd\xa6\xc5\xbew\x84\x1e,\x9c\x84Y/K\xf9\xbe\x16+{)\\\xd1\xdc\x1c\x94\xb7\xd2i\xfb/\xb4:(\xef\xa4\xa6\xf7\xd1Z\xcdz+<\xa1"\xa5\xcbi\xb0\xb4\x07\xbdfEH\xa7\xa8\'\xf9\x10\xb3\xa7E\xf5\xc4\xf2.jq\xde>\xee\xb0Y\x88\xe8\xdao\xed\xea\r\xf8\xc4BD\x07u\x1a\x92\xc0*\xc9^\x18\x10\xd1q\xea\xbbH\xdd;\x10:\xe4\x13,\xab\x8a\x8c\xc4\x14\xb8p\xb0\xb4\xe9\xbd\x01K\xf0B\xae\xcb\x8fX\x18u\xfb\xcc\xab\xea\xf7\xfb\xb6\xad\\\xf1\x0c\xebc\xf4\t\x85|\xeeA\xfc(\x95\xc6\xa9\xb5\xc8\'TVU\xa8\xe5\x82jK\xdd\x13\xca\x8bj\x94I\x1f\xf2\x18\\\xa5\xae\xeaC\xf0\x89\xe4%u\xd8k\xf9\xdc\xaa\xfd\x03R\xa4r\xfd\xbd\x8b\x9f\xc9\xea\x90\xbc\x9c\xf2oo\xcfdtH\x98@\xab\x04]\xb5\xadh\xdb$\xae\xf0\xe5LF\xad\x9f\xdc\xc8\xa8\xa4q[K\x88\xee\x86\x14\xc5\x95\xac6\xa3\x92\xc5u\xc9{\x8a\xbc\xe9b6\xb0P\xd95s\\\xd1\xec\xa0\xd83\xbbU\xda\xdd\x84\xea\x9b\xc1\x13*W\xcc\xa2H\x1a\xaaV\xc4\x9eH\x91\xc3]\x91\x81\xdb\xb4H\x11\xc3}\xcf\xee>a\xc9\x9ec\x81b\xa7\xc8\x97\xa5\xe0\x81r\xbb\xfc\xd5\xcf\xeb\xfe\xdd"\xbd\xa5 F\x8a<\xe8\xbeu|\x94\x96y\x83\x1a\xa4H\xdfI1&K\xe85\xfaapH1R\xa42~\x96w\xebw\xed\x8b\xc5\xc0Be\x11\xd5\xba\x04\'I\xc0\xea\xca\xa2\xa8\x04\xef\x10[\xf1at{]\xee\x88O\xa8\xc8\xdd\x96\xa7\xa0-|\x82B\xee\xb6\xb2\xaf\xc3\xbf\xe8\xf1=O\xde\xb9\'T\xe4n\x98\xb8\x83\xaf\xaf\x9a\x1d\x94\x17\xd2H\x1d\xf7\xfe\xe3\x87\'3\xd0\x13)ac\xdb\x9fM\'*\xad\x07S\x83\x88\x10\xbbe\xe6\x0b\xa9\x15\xda\x07\x12\x81c\xb1\xca8\xe1\xc04\xdaD\xe4X\xc3\xc9\x04\xeb\xb4E\xf2BJ\xb9\xe3\x8b\xd2\x17\xe9\x0e)\xebh\xc7\xf2\xc8\xdcfS\xa1L\xcaJ\x11U\x9b\xe3z\x18\x86\x07\x12\xd6\x1865\xec\xf5\x97\xcb\x0b\n\xf0\x13)\xe3T\xf6\xfb&\x17`\x8b\x94\xe3\xa5)/G\xbf\x8e\xf3\x89\xe4\xed\x92ndvH\xc4X\xaaq\xdeT\xdf\'R,\x149\x03]v\x9c\xf8z\x7f\x17;P\x18(\x8a6C\xb6W\xb0m@\x07+\xaao\x89C\xb5Klt\xba,\x17\xc8\x91\xd3Y\x07\r\xb6U\xe5\x17\x86\xee\x9b\xb4Q\x85g\xd9l\x18\xee\xb6_\xa5\xecj\x16\x99\x0e+ae!\xdc\xec1\xd3\xe9\xb3\x18\x8as\xfc\x9a\x95 \x87\x14\x949\xa6\xcbx\x8d\x8f$28w=^\xf8I,V\xce\xf26olzU\x93\xc5\xc2\x8aA\x9b\xdc\xc6k\xabK\x16,\xb6\x898\x9a2\xf5\xcd\xf2\t,K+\xe6\xbbW\xc9\x81\x95\xd1\xf8f\xaf#\x9d\xd4\x10\x1a\xcas\xa7\x97\xc7\x8a\x80\x19\xf6t!\x9aw\x9c>\x13\xcd\x96\xb3\x87E(\x1fsuA\xcd\xd5\x91!\x95\xdb\xbd\xd5\xea\xa0r\xfc\xcc+j\x0b\x8e\xac\xe4r\xbc\xad\x8cb\xcdS\xd6\xda\xf0\xd5\x04l\x06\x19\x1d\xa8\n\x7f\xb8\xba)\xa3\x83\x8a"\x133\xfb\xd0x\xefz\xa8\xec\xa1\x03_\x13S\x95W*\x19(\xb6\x10\x05\xc0Ved\xf7Z\x15\xd1<\x1bG\x15l\xb5"Z\xd6\xcc\x03\xe5\xed\x93\x82\x0eH t\xd8(\xb4\xe2[\xa3V\x84\xd2A\x8aE\xa2\xb5sl\x80\xdb&L\xc6q\xca$-\x1d\xd3\xf2\xfa\x1d\xa8d\xe3DVl\xd9Y\xd3\x1d\x92\x97\xd2\x88Q\x14\xf1\xa5\xb49\x8b\x10\x91\xbe#C\xdd\xdb\x0e"s5@#\xce3\xfep\xe8\xd8\xd2\xa0\xb23Gb\'\x1e\xbf"\xa2\xaf\x1f|\xe00<PD\x9d\xd5e\x8a\x90\xa1\x9a\xee\xd8\x03E\x04c\x19\xdb.P%\x9a\xc6\x9c_\x91\xc2\xb3\xac\xe8\x9f\xc8\xa4\x19\x13s\x90r\xbc\xb7 \xd7\xc8.\xd7\x06\x8b\x14\x1fp\x88\x12\xaf\xe6\xbb\x0b\x0fR\x94\xc5\xa2\xda\x0c<\xce\xb7\xa4N]kc_]\xf9\x92\xa3\xad5O\xa4\x84\xfa\xce\xf3\x9d\xd7ttD\x95\xbb\xb6\xe7\x07-\x16\x07\xe4Q\xd6r1\x9bD\x07\x14\xaf\x1d\xa2\xf9\x08\x8c^\x8b\xe2Wa\x8b@\xdd\xd3jJ\x13\x9d\xbd\xd6.\x1f\xe4tw|"E\xe4\x8e\xb4\x96:Y>\xda>\xd5\x8c\rZ\xb4\xcc\r\xda\xdeB\xed\x9aB\xb7h\xa1\xdb\xd6,\x91\x81h\x19N\xa6\xcd\x8a\xd4\x1d\xca\xfeA\xadz=F\x06\x1be\xd8\xac9mbO\xb0H%u\xf36\x80h+\x86\x85\xc2M\xd7 \x8c\x96\xb9\xb08\xa88\x16~\x1b]d\xddf\xd1\xe4\x90\xb2\x94\x1aK\xb1mP\x8d\x96K2\x16-v[\x15\x01H#\x8d\xce\x1eU\xb1gyl\x89\xbd\x8f\xa6\xe8\xac\x07\xe5\x9c\xeb\xe5b\x160\xcf\x89\xa2#&j\xc1\xb1F(\xcf\xf6\x1bT\xc4\xee\x18\xfa\xaaM\xb7\xa2\xe8\xa0\xa2\xfb\xe6\xae\xae\x82D\x1d\xdd\xef\x06\xaa\xc3}\x0f\x81\xb9#\x1f\xf6}\xcc"a\xd5\xd2\xf7O\xf2\r\x1c\xffE\xbb\xee\x91U\xc9l3\x02%\xb5\x8c\xd0n\x908b\xae\x01\x0c~\xab\xa2\xf9\xd6\xab\x0eZ(\xdc\xddb%B$+\xady\xb5k\xea\xea*\xb3\xed\x14\xa1\xb7\xee\x8f\xdd\xeb2o\x1dN\xa5B$#\xb5o\x90b\x96\x18\x11\x1fv\x9bWmR\xc4p\x9b*L\x89\xd0c\x11&\x03E\xf8oG\x14X\x13\xdd!\x1a\xa8\xec\x9cY\xe2\xb9U38*V-\x83\x11\xdb\xfa\x81\xc2\xa2\x92\xdcz\x9a\x97\xee6\x87\xe4\xb54r\x15\xe3\xea\xda\xe7\xcerP"8T\x18\xe3\xc8R\x99\x9c\x81\x8a\xe6\x9b`\x00\\\xc6\xb8\xe0\x90:JB,\xd0\x07\x90\xbd\x81\xc2\x07W`\x97\xad\xb4\x10\xa6\x83\x8a\x08\xae\xa9\xfc\x88\xb5\xbd.\xd4\xee/\xdc\n#\\\xce)\x0fE\xaed\x859\x98=\x7f&\n\x11\xbc\x93<\xd2"\xc32vZ\xa4H\xe0\x19\x7fVY\x80\xba\xba\x9b\x0f\xcaX\xf7\x88\x8b\xc8\x01$\xedpg\xb3A\xf3\r\xf1a\x8a\xde\xb6\xa9R\xdcR\x18 \x8f?\xb2\xb9KU\x92\xdbaH>\x91\xa9;m\x8a\xf9.^T\x16s\x82T\x9a[\x9d\x17\xb0:\xa0\xa8\xbe\xed\x87\x93]\xd7\xe2\x0bNWqM\xfc\x12\x14\x99\xdb\xe3M\xd1\xb1I\xc8\xdc2.\x8a\x8e)ONin\xa5\tJ\xee03\xb9.\xea4\xb79\x96\xec;~\xbc\xee\x97\xe6\xe2Sin\xa3#\xcfc\xd9\x0c\xbaC\xe2\xf2T\x1f.\xa6\x16))\x17\xb3\xa0\xb7\xf9\x936E\xe6\xc6\x94\xe4\xcb4\xc9\xa4\xb2PQ{K\xc4\xecRw=\x12v\xabP\xd0\xe8G(r.\x94W\x9f\xcd\r\xd5Z\x0e*R\xb8,\xbf*\xe6\xd7\x14b:\xc9-\x84\x84K\xdf1\xcb\x91\xa7\xfb\x1d\n\xb3\xef\xe0\xfc\xa6\xb0/\x9a\xce\xfeVi\xc5\x8bLLN\x07\x14\xd7\xd4\xaf\xae\xc1}#\xd7|t\xa4\x18\x94\xde\xd1hz\xfe\xe0Z\xec\x08\x15\x08\xdd\x16\x19\r\x1f\xe4\xaaE\x95\xe5vT\xa98~\xfb\'\t\x9a\x15\x1a\x1fP1\xf7\xa65?\xd4\xe1{\xabO(\x82\x1f&\xfd\xef\x7f\xb2\xb4Z\x1cTv\xcd\xaf^uA\xab\x83"\xbe~\x91\x18jpH\xd1x\xc7\xcf!n\xfflg\xcb\xf2\xcfZ\xa0\x94:\t\x0b$\xe9@\xa7\x92\xd7\xa4r\xc3\xd1\x92_m\xd2rh\x0e\xaa\xa2\x84\xb1\x92(\x96\xcb\x9d"\x89?\xa3\xcaIlt \xcai\x15.\xb8Q\xc4\'\xb2L\x1d\xc7\xaf\xbbA\xf2B\x9as\\v\xb8\xf6\x91<\x91\xb2\x8e\x8e\xd0\x1d\x96\xf8w\xe9\xfb\x84b\x1d\xa5\x08\x91/i\x04\x16*\xf1\x0f5\xc7\x8b\x0c\xf5Z\x15\xf1[S\xbf\x1cn\xceRR:o\xbd\xa2\xceW\x15\xf1;g\xdf\x86L\x96\xbe\xce*\x14\xe9\xdb[\xbd\x98@\x1d\xe9\x80\xb0\xb38/\xa4#\x1c\x10v\x96V\x9b\xb2\xc1\xa7\x03\x8a\xec\x8d\xf5\xbba\xaa\x8a\x0eC\x9a$\xd2\xf9\x9e\x90\xbc5\xa0\xc9\xf1B\x9e\xd2#\xa8R\xe4\xf2\xc8_\xb4\xa8\xf2\xe3R\xe3\xae\xeeA6k\xaf\xa8\xec8\x80{Z\xb55\xe6\t\xc4NY\x8a\x06\x81\xe5\x83\x16E\xde\xae3\xf4\xf8g\xf0\xef-NB\xcd\xb8\xaaP]%\xa9\xaa\xc3\x89\x91\xb7|\xc7\xc9\xf6x\xa8~dqHb\nh0\xbfx%\xbc\x07%6(\xb4\xad]\xec\x9e:3\x8a:\x0eJ-\x91\xbck\x0b\x14\x11\xbb[\xa4\xa3\xbal\xb0\x18\xa0H\xd8T\x8a\xe8P8\xe4\x8dQ*\t\xfb{\x17\xfc\x0eEdoT\x9a\x1b\x89\xb9\xe2\xa0\x880\xab\xe1\x82f\x07\x85\x82\x1b\xb9\xf2V\xe0"J6)\x01fe\xd5%\x93\xbdej3*\x0f\xae\xcd"\r\xec\x8aV\xd5\x04%P1n\xe5+\xf0\xaa5\xcf\x11\x95\x04\x97\xfbZ\x06\x01\xcb\xddlRE\x97\xad\xdfE\xee\xab3H\x04\x97\x95\xf9\x1d(+\xe8wg\x92\xfa\x14\xb1Q\x0cRg\xc0\xa5A\xbf!\xc5\x8b\xf6\xa6i\xddW\tpu7\x99xS\x9bng\x95\xff\x96\xf1\xf7oaPMN\x8e\x90\xb4\x1a\x0c\xdc`v@\x89^h<9\x81\x0b\xcc\x19\xc1C\xf3dJ8\x18\x80\xcd\x01aJH\x8a<~\xd9\xd7\xaf\xdf\x92\xca|[/hs\x86\tm\xb6\x16\xb5\xd4\x0b\xb5j\xf7\x17!e|\xbb9\xed\x12\x03U\xf9nkG\x8b\x14\xe9vw\x11M6\xc6\x0f\xc7\xf7u\x0e_\xb3@1$$\x14\xe3 \xfdy: /\xa0\x19\xd5]5\xbc\xdc\x15\xabb\x16\xaa\xa8\x12\xad\xbd\xdcy\x85\xe16,U\x82\x94\x01\xa2_\xf6\xac\x9etX>\xf9\xe8f\xe2,=U\x98\xac\x97\xbd3\xf6u\xc8\xb4\x15\xab\xac\xb6TK\xbe\x93V\x9b(\x92S\xd6mHn\xe4\xcer\x87\xcdv\xe6\xbdz\xeaZ=\xce0a\xb2\xdd7y\x02W\xc8\xb2\r\x8a\xf4\xa9\xab\xae\xab\xacWg\xd9!\xcbx\x17\x92\x953/\x19cL*\x87m\xe0\xd4\x18</\x16\'Z\xfa\xfc\x81\xd8\n\xaf\xf3\x91\xf7\x04\x8aQz\xfd\xcf\x10[\xbc?\xdf\x81p\n.\x01\xb0D\xec\xf1\xcb\xe2\x90\xaa\xb6\x035G&\x83\x8f\xdaT\x05r\xfe\x9c\xc5\xbae\xf0J*k\xed\x08\xed\xbc4j\xd9\x81\x92\xceZ\xeb3n\x96t\xd2\xb67\x98\xc5\x8a\x98=BY\xfflc\xc5f\xbb\xd3.\xe4l\xbc\x1e\xb7\xd3Fa\xb2\r\xed\xbc\x8c,kdR\x19k-\xb7\xbdS\xc2\xda)\xcd\x01\xc5I6\xcb\xde\xd4\x1b\xf4\xba*r\xb65:bI\xce\xb2M\xd0j\xb1\xa81\xf2\xb0(\x90#F\x87\x94U\xb4\xaf&\xb2\xabMSx:e\xa9\r\x85\x0eF\x8d\r\xaa\x82\x14\xb4\xd9\x94P\x96,\xefP\xc4\x86\xa5r\xe9\xb0\x87*a;\x80\xd2\x97u\xf6\x9a\x8a\xd0U\xe4\xf1\xc3\xe8\xec5\xc4\x86\x85\xbcoA\xfb\xcc\x8d\xce*\x82\x87\xac\xf4\x0bi\xf9\x9c\x92\xcaSKu\xca\xcdk\x91+n\xf0\r\xa9\xf2\xd4b\x8d?b\x9c[S\xc4.\xc5w\xa8\xf87\xd6\xa7W\xa6Z\xafQ\t\x82kL\xf2%n\xbe\x8cu\xa4\xd2\xd4R\xb9\x92\xac\xfb\xbf#\xc5I\x16\x15I_\x96-$\xefHUx\x97H\xd1\xf7\xcc\xd8\xc4\x14\xb5\xd8M\xaaQB\x87\x83B\xb9=M\x92\xb0\xd6$!8\xa1\xd6oYx\xca\xfa\xb7\xedB\xee\xa6xE\xbb\x83"\xda\xe5\xd6jsP\x91\xbd\xa1>\xb5jL2\xaa\xf0\xa6\xb5\xf8\x8f\xdf`MX\x8d\x8a\x19*<\x0e\xd5X\x88(\xabS\xe7\xd3\x04[\xa8\xaa\xab\xd3\x9f\xa6\xc9b\x11\xa3\x10\xb2Z\xc74\xda\xe2\xb0Pw\xb7\x11#H\xb3\xd1AU\x90\xc2\xbc\xa0\xc7\x7f\x19_G)\xbc\xfc-*l\xb6F\x9b\xe9\xba\x98D\xfdt\xe6\x08\x02x\x84;h,\x07e\xb2Eyu\x02\x8f\xffx+\xb8u\xbeZ\x1e\x04%\xfe&\xc9\x01%\x94=B\xc3\xee\xfb_\x92\xc1\x89\xe8-w.\x1b\x9c\x8c\xb0K\xd7\xc4\xc0S\x0cN\xb4\xddy\xe5\xec\xf6\xa0\xa5|\xc7\xa1\x86\x19\x1e\xbf\x90\t\xb5@\x08\xdc\xfe\xcd\xa5E\'\xa8\xb1E@\x0e%\xaf\xb3\x10\xb61\xca\xe7\xef|\xc56H\xe5\x18\x9b\xf7\x8b\xbd\x05\xca\xa1\x1da\x11h\xe2<\xb4H\xb1%DTZ]\x81\x1b\xbcU\xde\x91\xa2\xe4f8|j\xff\x84\x14-w\xe7yK\xcc\x90\xad\x85\xa9\x84\xb4#\xc8\x94\xf5\xb7\x15+\xe2\xb5\x89P\xdc\x04\xd5\x8fJ\xf4D\xef\xab\xa0RN=\xe4\xb3\xa4z\x7f\x80"\x0el\xeb\n\xc7\x8f\xc8I\xea}Q%a10Z\x0b\x96\x15,\xa9,\xb4\xf1\x04\x1a\xc2\x07\x02\x96\xaf\xcd\xb4W\x16i\x8a-\x15\x046\xe47\xab8\xa1\x03\xc2\xa2YV\x93\x91\xc9l\x91*\xf9\xec\xa8\xea\xf9g\x9b_\x8f\x15\xf5\xaa\'\xeb\xf4\x13*\x1e\x8e&7_"\x9dq\xaa\xdc\xb3\xdf\xdb\xc3\x03Y\x0c\x92\x07Z\xb8\xb7\xa4V\x1f\xb8)Mt\xe6\x19\xdf\xd3\x13\xb7\xe9\x91\xda\xb0\xf0]o\xc5z\x9b\xda\xea)\xd9\xb6\xc7\x8a\xc3\xb5\xa7\x08\xe5p~/\xcd0,\x0c\xf6;Z\xac\x88\xdcc\x8f\xc2\xb0@\xd3d\x1a\x16\xb26,\xe4m-\x923\xc2i\x16\n\xeeTVc\xb1\xe0Z$b\xc1\n\x04\x03A\xe6\xc2?e\x9e\r\xcel\t+}"z\xddE\x00nEn\x0b\xc7\x14\xd8\xa88\xcb\x8e\xd8]\xfe\x92\xf7\xca\'Oh\x05\x9a`\x9a\xd8\xad\xdac\x15\xd1{\xc4O\xc8\xad\xdb\xbf\xea\xeb\xe4\xb3<\xc6\x05-\x0e\x8a,\x88\xd2\xe4\x94Y\xd5\xc7\xcdSF\'\x9f\xc5\xc4\xe5l8<\xc0\xaaS\x9cT\xf2Y\x1b\xfd\x87\xc3=\xa9\xd1\xe44\x8a\x90\x84\x84H\x91\xa5\xc3\x1d\xbf\xee\x06)N\xb3\x80\xa2 \x8b\xcc\x0e)\xf7\xee\x89\xd8\xe8E\x9aw\xe0\xd3\xbbiMRL\xc8\x8aw\xca\xed\x8e\x0f\xa4\x84\xe0\xaa8\xf9\xf50\x8b\x15]\x90\xf4\xcbi%\x9dgh}\x95f\xa0\xb2gR\xfc\xe1\xe0\x1f6j@\x88>\x91\xb8\x12\x1a+\xe1\t\x94@\xb0\xf8#Y\x88\x99\x17B4@\t\x04k\xb2EQF\xdc\x02!z\xafe\xe8\xbd&E\xf0\xc6!\xc2\xa8oad\x93(\x19u\xcd\xb3\x1b6\x89R\xbda4\x99!\xbf\xdaOR\xa9g\xf1x\x90\x85\xcdo~\xbd\x9f\xa4s\xcf\x0ec\xb0\xa0\xf1\x13T\xd6Po\\Xk\x07*\x9b\x15\x9c\x92~;\xad\xcf&Kw\xa1\xe1\x15\xace\x04\xb9\xdb\'\x82\xdd?kU\xe4\xee\xf1\xd2\x93\x049K\xc8\x9b\x85\xcaRJ[\x02R\xab\xb4\x18\xaa\x83J\xf9\xb1\x8c\xe2\xfbM\xac\xc9\x16)k) \x0el\x91\xce\xa7Qq`J\xd4\x87\x0f\xdaD\xf9\xb1y\x8d\xfb\xf5H\xf8\x98\xd8\xcaT\x95\xc1\xdd"q\xe9\xde\xe6N1\x81\xd8\xa8J<\xcb\x05\xef\xe1}F"$c?s\x18\xf9\x940\xa3\xec\x92\xce;\x8b\x8dQn58\xa8\xec\x19~\xaa\x90\x942j\xb58(t\x95\xae\xd0\xf2\xc9X\xc5\x16\x17\xbe\x1d*o\x99\x91\xaf\xdd\xf5\xdaD\xc1\xbeqE\xab\x83\xca%1\xe9G\x19\xe3\'\xa8\xc4\xf6\xa4\x89Exs\xdd<\x90Pzk\x97\xcd\xb6\xb6\x0c\xbb\xe9\xdf\x91\xc8\xa1\x99\xcbWH\xc2l\xf0\x9e\xb1P\x9c\xe0}H\x89kz\x00\xe2\xf4\xb8\xd0\x13\n\xe9\x1b\xaaT\xe6j\xfb$\xb6\x87\x8a \xdcxM\x93K\x0e\x8a\x10\xb1~\xad\x07\x16\x1d\x14V\xdd<\xce\xa8\xdba\x89\x11\xeb\xf5Bz\xb3$\xc2\x97j\xa5o\x92$\xbeG\xcaJj\r\xa4\xdc\x0c\x0cR\x84\xef*[\xae\xc9\xe1\x90"|3\xc6\xb9\xde=\xd1\xae\xa6\'RD\xd2\xec7\xd2\\\x82\xea\x95\x9f\xf0\r\xa9\xb2\xcebT\xbd\xedk\x86\x0ceY?\xad\xc6\x85\xec\xaa\xe8\xad\xc6=\\\xbf\xad\x86\xc4\xd0\xa5\x9e\xc7W5A9b\xf2\x19\xa4\x8fi\x81\xe2O\xebR\x84\xe5\x03\x7f\xcd9\xe9\x8c\x13t\xf1\x08\x82\x05\x9e"\xc5\xc2k]\xba\xb1\n\xacy\x85q7N\xc5\x0ef\xadf\x11+66{`\\o\xc9\xee2l\r\xa5\xa0\xa4\x0f\x17\x122\xdbE\\n\xc8\xaa\xcb\x846{\xb8\xf0\xa6\xa5\xf3\xa3\x0f\xd5.M\x91T\xea\xd9\xd0\x85\xda\x1a\xd9\xa6\xcd{\xa9\xca=\x1bC\xbd\xbcS>\x19\xaa\\\x9d\xa6\xaa\xcbs\xfc\xd0\xac\xb8\x90\x9a\x8e\x1aC\x01\x83\xf5NPvH\x98y\xa5\x0c#\xa34Q\x06\x8a\xb81%\xc8\xf8p\xb2[\x85\'-\xcc\x9fs\xb1\x06}\rzB\x11\xccP;\xae\x06t8\x05\x1bU\x85n\x9erK,Rb\xc7j\xc0\xc5@\xb2\x1f-\x12\x96\xde,\xf7\x02d\xe7Y$\x04o\xb9\x90\xa6IQ?\xaf\x96\xb3\xdc(>hS?\xaf\xa6\x12K$k\xd2\x02U\x84\xae\x80\x1f\xb5\xa8\x04\xef\x19L\x0e(\x82\xf7[P\t\xde\xf3\x1b{\xd9\x01\xc5\xa7\xd6\xe3\xfe \xf5\xc3&E\xee\xce\x98\xbf\xfc\x96\xf0\xaa\xe5z\xe9\xaf\x87\xc2\xad\x16\xb0j\x97r\xc33\xf6\x06U\xd9\xbe\xc8d]\xe4pH9\xba\xd5\xd3l\xac\x8a\xd9\xa48\xd6\xe6E\xe94\xb3}\x93~`\xad\xf7\x0biJ\xdc\xae\x1dk\xd7Jh\xa6\xbbIe\x9b\x1d\xf1!k\x9cU\x95|\xb3HH\xdc\xb2\xd0&S\x14\x1dTI\xdc"\xb9E\x84v\x87\x14\x81\xdbk\xf8\xb2QT\x16\xcb8!P\xcf\xcc@E\xe0\xc6\x10"N\x08\xff,\xec\xda\xb7\x86\xf7\x84p{)\x06\x89\xa8*\x98\x8e\x90\xcbg\x91"\x8bZ\xba\x90f\x9b\xfaU\xb6\x19.\xfb\xc5\x1c\xa7\xca9\xeb0V\xa1\x82\x9a\x05\xca0\xfb\x05LN_y\x94\x15\xd5\xee\x97\x7f\xbf:\xa0\x8aa\x90e\xf0Q\x8b\xb2W\x00\x0eQN,\x10\x12\x97+\xa7\xd4]\x92\xb18\xb3\x83\x14\xdf\x8c\x9d\xfd\x81\xa5~hE\xb7\xeb\xd7\xf9\xc6\'\xcd\xca^\xe9\\$\t\xacy\xe9Q\thG\x94\x9c\xe8\xc8\x93v\xa7v\x11<\xa1PO\xc6\x8f<\xf4@\x15zW\x91$\x03\xe5e\xd4v\xc9\x96\xc4g\x04=/a5\x9a\x85\x9c\xdbcX?\xa8A\x95T\nZ\xdbE\xbe\x8e\xfe\xad\x12(\xa6\xa4W\x19h#ei\x93\nn\xb8$\xac\x0bmUX8z\xbaj\xa0\x14\x07E8CZ\x86\xf7c\x86\x17\xcaA\xce\xefP\x11\xbb\xb9/\xabQ\x90V\xa3\x83B\xcf\x8dy\xa3\xf5\xe1q\x89\x07T\x054\xa8\xd2x\xebu\xa5\xee\xa0"vkR(\xa9\x0b\xd3AE\xd3\xad\xf1[TT\xdd\xbe\x1e\xd9\xfd#\xd9 \xe6#V\xe9\x94\x8d\xb6cKI\x11\xac<M\xc9@\xc5.\x17\xb6\x19\xf1\xf8\x83\x8c\x81\xe6\x93]i\x9e\xec\x0c +\x93V\x7f\xe5\x8c\x19\xdc\xddm\x057\x8b\x15%\x9d\x93\x96\xaf\x03\xf5\xe6H\xcc\xbb\xed[\x12\x91\xbb\x13\xe8\x90\xb3\xdfB\x910\xd1\xc2\x95\xa5?\x0c\x16\t\x13#_\xd9\xe2\xb0J\xeb]\xd7J\x84r{+\x02jod\x1fd\xd8\x1e\xb6\xee\x90\x08\x02\x0f"]\xc8sd\x96\x93O*7m\x0c\xc8%~\xdc\xa2\x9a\xa4\x18\x1a\xa8<\xce\x16\x86$F\xcd\x9b\xbb\xcaN\xeb\xb5?\x90V\x9b\x92?>\x82\x9a\xdc\xb1v\xaaq^\xa8\x04\xb5\xe3\x15\x0f\x92\x0f\xdb\x01T\xed\x12jIe\xa8\xc59$\xe0\x9d\xb7Mp\xc6\x8a"7\x88\xe4f\xc7\x93\xb3\xe5\xf4{\x98\xfd\xbau\x9c\xb5\x84\xcc\t\xce\x0b \xf4\x93e\x08kCZ\xe7\xf1\x1f\x89\xa3]\xe6\x9cf\xb0\xb07\x04\xb0\xddW^T\xbaZ\x8e\xe5:Xk\x11\xe7p\xd6\x7f/hqP\x89\xe0\xbdI\t\xfa;\x0c\x92\x87\xdau\x009\xa9\xeb\xdd!Eu9\xfe\xa7\xaaV\xa2i\xce\xc9*k\xad\xc0*\xbc\xdcGV\x91\xc5\xac\x92\xd6N.LjMV\xd3;T\x07\x97\xad\x99\xacH\x003I\xd97G4\xd0\xb1\x10\x8e\x1fQv\x9e\x8b\x8a\x08>\n\x93\x1f_bek\x1f?5M\xc5Y\xe7\xac\xb5\xd6\xc1\xfaf\xf1\xac_Zk\xaaT\x93\x9f\x8c\x90\x836=$|\x9c\xca\x1dN\x06)\xa6\x87\xa6*`S\xec\xc9\xf1k\x8b\x14\xd3C\xca\x97\xc0\x8a\xec\xf4VL\x0f\xaa\xe2\xd7\xddQ\xf6D\xa2\xb6\xa3\xaa\xaeC\xeb\xde\xbalf\x9d\xb9Vj\xba\xa0\xcd\x99"\x04\x96\xd5\x00;T\xe0=c\xa1*\xb0,\xc8\xf4\xfaAtYg\xae\xc5\x1c\x7f8P\x01!\x0eF\xab\x90\xbf\xf2f\x19\x93\xce\x1e\x87\xf8\xdd\x05=\x90\n\xd6\xec\xee\xaa:c\xb7@\x05Kg\xcf\xfa\x89\xb5\xa9RZx\xf5\x1a\xa8~c\xadO\xdem\xe1\xa1\xd5\xf8\x80J\x90\xc3\xce\x9f\xc0Is\n\x8d|B\xc5\xa3Xw\xa4B\x96V\xa7\x83"\xc8!\xd3\xff\xfeG\x02\xf0\xcc8\x9b\xac\xd2\xd7f\xbb\xf6W\xfb\xa0\x9eH\x15\xdc{\x11It86\x03\xe5m\xa3c2H\x00\x9f|uO$\xc2\x82nIN\xcdkU\xb6\xcd\xb8e\xcdi}\xe9\t\x95"8m<5k\xa0\x90\xbf\xf742\xad\x04<\xa1\x12&\x9e\x9a\xc8_$BZ\xa4\xe8\xc0\xf1\x89\xb4\xba+a\xe2\xe11\x8b\xccBy)\xd5\xa4R>\xd7\x017\x9dV%T1s\xdd\xc4\xb0\x95\xe0\xe8\x90\x12\xab8\xab\xd8\x03V%7mp~"Q\x07\'\xa0M"\xb5A\xeb\x89\x94B8\xfa\xddGZ\xf4\xc9!\x11\xe3\xc0\xbd\xdd\xf1p\xb4p\xcb{\x121\x0e\xa5\x0bY\xc5rg\x91\x12\xe3\xa0\xafo+~\xcf\xd9m\x

In [6]:
# unzipping dataset

with zipfile.ZipFile('archive.zip', 'r') as file:
    file.extractall()

In [7]:
# converting 'london_merged.csv' into pandas dataframe 'bikes'

bikes = pd.read_csv('london_merged.csv')
bikes.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [8]:
# quick summary
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

In [9]:
# the shape of dataset

bikes.shape

(17414, 10)

In [10]:
# display first 5 rows

bikes.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [11]:
# count of each unique vlaaes in weather_code column

bikes.weather_code.value_counts()

weather_code
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [12]:
# count of each unique values in the weather_code column

bikes.season.value_counts()

season
0.0    4394
1.0    4387
3.0    4330
2.0    4303
Name: count, dtype: int64

In [13]:
# specifying the new names for the columns

new_cols_dict ={
    'timestamp':'time',
    'cnt': 'count',
    't1':'temp_real_C',
    't2':'temp_feels_like_C',
    'hum':'humidity_percent',
    'wind_speed':'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday':'is_holiday',
    'is_weekend':'is_weekend',
    'season':'season'
}


# renaming the columns with their new names

bikes.rename(new_cols_dict, axis=1, inplace=True)

In [14]:
# noramlizing the humidity values

bikes.humidity_percent = bikes.humidity_percent / 100

In [15]:
# creating dictionary for mapping the values 0-3 to the seasons names

season_dict = {
    0.0 : 'spring',
    1.0 : 'summer',
    2.0 : 'autumn',
    3.0 : 'winter'
}


# creating weather dictionary to help us map integers to the actual written values

weather_dict = {
    1.0 : 'Clear',
    2.0 : 'Scattered clouds',
    3.0 : 'Broken clouds',
    4.0 : 'Cloudy',
    7.0 : 'Rain',
    10.0 : 'Rain with thunderstorm',
    26.0 : 'Snowfall'
}


# mapping the values 0-3 to the actual written seasons

bikes.season = bikes.season.map(season_dict)


# mapping the values to the actual written weathers

bikes.weather = bikes.weather.map(weather_dict)

bikes.head()

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,winter

In [17]:
# writing final dataframe into excel file

bikes.to_excel('london_bikes_final.xlsx', sheet_name = 'Data')